name: Pull Talawa API and Admin Changes

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.email "${{ env.email }}"
          git config --global user.name "${{ github.actor }}"
      
      - name: Run bash script for docs API
        run: bash .github/workflows/pull-docs-api.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run bash script for docs admin
        run: bash .github/workflows/pull-docs-admin.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}